Time::DATE_FORMATS[:slash_time] = "%D %H:%M"
Time::DATE_FORMATS[:slash_date] = "%D"
Time::DATE_FORMATS[:wordy_time] = "%B %e, %Y %I:%M%P"
Time::DATE_FORMATS[:wordy_date] = "%B %e, %Y"
Time::DATE_FORMATS[:blog_time]  = "%I:%M%P on %B %e, %Y"
Time::DATE_FORMATS[:service_timestamp]  = "%Y-%m-%d %H:%M:%SZ"
